spring:
  application:
    name: taskflow-backend

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  servlet:
    multipart:
      max-request-size: 1MB
      max-file-size: 1MB

logging:
  level:
    root: INFO
    com.franco.backend: INFO

server:
  tomcat:
    max-http-form-post-size: 1MB

security:
  rate-limit:
    login-per-minute: 5
    refresh-per-minute: 10
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: ${JWT_ACCESS_SECONDS}

management:
  endpoints:
    web:
      exposure:
        include: health,info
